# Generated by Django 5.2.7 on 2025-10-18 18:09

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MorSh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Father_Name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('M', 'کارت ملی'), ('SH', 'شناسنامه')], default='M', max_length=2)),
                ('date_S', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MorSh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
